### ISSUE TITLE
attempting to connect to 1.6.4 server disconnects u immediately

### ISSUE THREAD

**Issue by mc-enjoyer** [RaphiMC/OpenAuthMod#1]
i try to connect to alfheim.pw and it doesnt work

**Comment by RaphiMC** [comment]
What mod loader are you using and what other mods are loaded? Also send me a screenshot of the error or a more detailed description of what exactly happened. The issues here are ONLY regarding OpenAuthMod and not ViaProxy! For ViaProxy support you can join the official discord: https://discord.gg/dCzT9XHEWu

**Comment by mc-enjoyer** [comment]
yeah this was resolved in the discord, apologies
