### ISSUE TITLE
Option to always allow auth for VIAaaS running on localhost

### ISSUE THREAD

**Issue by jschenke488** [RaphiMC/OpenAuthMod#2]
Config option to always allow auth for VIAaaS running on localhost

**Comment by RaphiMC** [comment]
Adding a config option (and a config screen) is not that easy when I have to support 1.8 up to 1.19.2 (Both forge and fabric). Every bit of minecraft code I use significantly increases the time it takes to update the mod. I might consider always accepting auth requests when joining to localhost servers. I will ask the VIAaaS maintainer first tho

**Comment by RaphiMC** [comment]
The feature will be added (Most likely with the next minecraft update)

**Comment by RaphiMC** [comment]
This feature has been implemented in OpenAuthMod 2.1.3
